Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Wodka")
Ingredient.create(name: "Sekt")
Ingredient.create(name: "Aperol")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Sparkling water")
Ingredient.create(name: "japanese")
Ingredient.create(name: "whiskey")
Ingredient.create(name: "vodka")
Ingredient.create(name: "flower water")
Ingredient.create(name: "simple syrup")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Club Soda")
Ingredient.create(name: "Matcha")
Ingredient.create(name: "Sekt")
Ingredient.create(name: "Aperol")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Sparkling water")
